// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YelgLens.Intake.DAL.Data;

#nullable disable

namespace YelgLens.Intake.DAL.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260907173847_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RemoteIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("IdentityRoles", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityRoleClaims", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<long?>("CurrentClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("IdentityUsers", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserClaims", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserLogins", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityUserRoles", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("IdentityUserTokens", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ArchivedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AttachError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FileRemovedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("OdooAttachmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdooCustomerOverride")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OdooDatabase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("OdooOrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("OdooOrderName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("OwnerDatabase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PublishError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PublishedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReopenNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("ReopenedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReopenedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ReplacesDocumentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("ReviewedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("SourceSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.Property<long>("UploadedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("OwnerDatabase");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("ReopenedByUserId");

                    b.HasIndex("ReplacesDocumentId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SourceSha256");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("IntakeDocuments", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("IntakeDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LineSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntakeDocumentId");

                    b.ToTable("IntakeIssues", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("IntakeDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IntakeDocumentId", "Sequence");

                    b.ToTable("IntakeLines", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakePage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long>("IntakeDocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<long?>("OdooAttachmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("IntakeDocumentId", "PageNumber");

                    b.ToTable("IntakePages", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Mapping.BranchMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("AutoCaptured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("FirstSeenDocumentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long?>("ModifiedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("OdooCustomer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OdooDatabase")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OdooDeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OdooInvoiceAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OdooPricelist")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OdooDatabase", "MatchKey")
                        .IsUnique();

                    b.ToTable("BranchMappings", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Mapping.OdooCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastSeenDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ParentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StoreNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("SearchKey");

                    b.HasIndex("StoreNumber");

                    b.HasIndex("Source", "Name")
                        .IsUnique();

                    b.ToTable("OdooCustomers", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Settings.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifiedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Settings.ClientUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifiedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClientId", "UserId")
                        .IsUnique();

                    b.ToTable("ClientUsers", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Settings.OdooConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("AllowWrites")
                        .HasColumnType("boolean");

                    b.Property<string>("ApiKeyProtected")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<bool>("AttachSourceOnPublish")
                        .HasColumnType("boolean");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DeleteLocalAfterAttach")
                        .HasColumnType("boolean");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastTestResult")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastTestedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ModifiedBy_UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Note")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ServiceUser")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Name")
                        .IsUnique();

                    b.ToTable("OdooConnections", (string)null);
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.RefreshToken", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.RoleClaim", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.RolePermission", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YelgLens.Intake.Model.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserClaim", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserLogin", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserRole", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YelgLens.Intake.Model.Auth.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.UserToken", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeDocument", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Auth.User", "ArchivedBy")
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YelgLens.Intake.Model.Auth.User", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YelgLens.Intake.Model.Auth.User", "ReopenedBy")
                        .WithMany()
                        .HasForeignKey("ReopenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YelgLens.Intake.Model.Documents.IntakeDocument", "Replaces")
                        .WithMany()
                        .HasForeignKey("ReplacesDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YelgLens.Intake.Model.Auth.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("YelgLens.Intake.Model.Auth.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<string>", "BranchLabel", b1 =>
                        {
                            b1.Property<long>("IntakeDocumentId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("BranchLabel_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("BranchLabel_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("BranchLabel_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("BranchLabel_Raw");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("BranchLabel");

                            b1.HasKey("IntakeDocumentId");

                            b1.ToTable("IntakeDocuments");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDocumentId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<string>", "CustomerName", b1 =>
                        {
                            b1.Property<long>("IntakeDocumentId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomerName_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("CustomerName_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("CustomerName_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("CustomerName_Raw");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("CustomerName");

                            b1.HasKey("IntakeDocumentId");

                            b1.ToTable("IntakeDocuments");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDocumentId");
                        });

                    b.OwnsOne("FieldValue", "CustomerPoNumber", b1 =>
                        {
                            b1.Property<long>("IntakeDocumentId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomerPoNumber_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("CustomerPoNumber_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("CustomerPoNumber_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("CustomerPoNumber_Raw");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("CustomerPoNumber");

                            b1.HasKey("IntakeDocumentId");

                            b1.ToTable("IntakeDocuments");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDocumentId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<System.DateTime>", "DeliveryDate", b1 =>
                        {
                            b1.Property<long>("IntakeDocumentId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("DeliveryDate_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("DeliveryDate_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("DeliveryDate_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("DeliveryDate_Raw");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("DeliveryDate");

                            b1.HasKey("IntakeDocumentId");

                            b1.ToTable("IntakeDocuments");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDocumentId");
                        });

                    b.OwnsOne("FieldValue", "OrderDate", b1 =>
                        {
                            b1.Property<long>("IntakeDocumentId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("OrderDate_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("OrderDate_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("OrderDate_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("OrderDate_Raw");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp without time zone")
                                .HasColumnName("OrderDate");

                            b1.HasKey("IntakeDocumentId");

                            b1.ToTable("IntakeDocuments");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDocumentId");
                        });

                    b.Navigation("ArchivedBy");

                    b.Navigation("BranchLabel")
                        .IsRequired();

                    b.Navigation("CustomerName")
                        .IsRequired();

                    b.Navigation("CustomerPoNumber")
                        .IsRequired();

                    b.Navigation("DeliveryDate")
                        .IsRequired();

                    b.Navigation("OrderDate")
                        .IsRequired();

                    b.Navigation("PublishedBy");

                    b.Navigation("ReopenedBy");

                    b.Navigation("Replaces");

                    b.Navigation("ReviewedBy");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeIssue", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Documents.IntakeDocument", "IntakeDocument")
                        .WithMany("Issues")
                        .HasForeignKey("IntakeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeDocument");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeLine", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Documents.IntakeDocument", "IntakeDocument")
                        .WithMany("Lines")
                        .HasForeignKey("IntakeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<string>", "Barcode", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("Barcode_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("Barcode_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("Barcode_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("Barcode_Raw");

                            b1.Property<string>("Value")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("Barcode");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<string>", "Description", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("Description_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("Description_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("Description_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("Description_Raw");

                            b1.Property<string>("Value")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("Description");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<decimal>", "DocumentUnitPrice", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("DocumentUnitPrice_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("DocumentUnitPrice_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("DocumentUnitPrice_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("DocumentUnitPrice_Raw");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("DocumentUnitPrice");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.OwnsOne("FieldValue", "OrderedQty", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("OrderedQty_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("OrderedQty_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("OrderedQty_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("OrderedQty_Raw");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("OrderedQty");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<decimal>", "ReceivedQty", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("ReceivedQty_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("ReceivedQty_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("ReceivedQty_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("ReceivedQty_Raw");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("ReceivedQty");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<string>", "SupplierSku", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("SupplierSku_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("SupplierSku_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("SupplierSku_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("SupplierSku_Raw");

                            b1.Property<string>("Value")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("SupplierSku");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.OwnsOne("YelgLens.Intake.Model.Documents.FieldValue<decimal>", "VatPercent", b1 =>
                        {
                            b1.Property<long>("IntakeLineId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Confidence")
                                .HasColumnType("double precision")
                                .HasColumnName("VatPercent_Conf");

                            b1.Property<bool>("HasValue")
                                .HasColumnType("boolean")
                                .HasColumnName("VatPercent_Has");

                            b1.Property<int>("Origin")
                                .HasColumnType("integer")
                                .HasColumnName("VatPercent_Origin");

                            b1.Property<string>("RawText")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("VatPercent_Raw");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("VatPercent");

                            b1.HasKey("IntakeLineId");

                            b1.ToTable("IntakeLines");

                            b1.WithOwner()
                                .HasForeignKey("IntakeLineId");
                        });

                    b.Navigation("Barcode")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("DocumentUnitPrice")
                        .IsRequired();

                    b.Navigation("IntakeDocument");

                    b.Navigation("OrderedQty")
                        .IsRequired();

                    b.Navigation("ReceivedQty")
                        .IsRequired();

                    b.Navigation("SupplierSku")
                        .IsRequired();

                    b.Navigation("VatPercent")
                        .IsRequired();
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakePage", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Documents.IntakeDocument", "IntakeDocument")
                        .WithMany("Pages")
                        .HasForeignKey("IntakeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntakeDocument");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Settings.ClientUser", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Settings.Client", "Client")
                        .WithMany("Users")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YelgLens.Intake.Model.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Settings.OdooConnection", b =>
                {
                    b.HasOne("YelgLens.Intake.Model.Settings.Client", "Client")
                        .WithMany("Connections")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Documents.IntakeDocument", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Lines");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("YelgLens.Intake.Model.Settings.Client", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
